[workspace]
members = [
  "parser",
  "gui",
  "renderer",
  "state",
  "animator",
  "video",
  "repository",
  "import",
  "bindings",
]
resolver = "2"

[workspace.package]
edition = "2021"
repository = "https://github.com/cda-tum/mqt-naviz"
