name: CI
on:
  push:
    branches:
      - main
  pull_request:
  merge_group:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  change-detection:
    name: 🔍 Change
    uses: ./.github/workflows/reusable-change-detection.yml

  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Install required dependencies
        run: |
          sudo apt update
          sudo apt install -y git curl
          curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
          sudo DEBIAN_FRONTEND=noninteractive apt install -y nodejs
      - name: Print versions
        run: |
          git --version
          node --version
          npm --version
          npx commitlint --version
      - name: Install commitlint
        run: |
          npm install conventional-changelog-conventionalcommits
          npm install commitlint@latest
      - name: Validate current commit (last commit) with commitlint
        if: github.event_name == 'push'
        run: npx commitlint --last --verbose
      - name: Validate PR commits with commitlint
        if: github.event_name == 'pull_request'
        run: npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose

  rust-linter:
    name: 🦀 Lint
    needs: change-detection
    if: fromJSON(needs.change-detection.outputs.run-rust-linter)
    uses: ./.github/workflows/reusable-rust-linter.yml
    with:
      build-project: true

  python-linter:
    name: 🐍 Lint
    needs: change-detection
    if: fromJSON(needs.change-detection.outputs.run-python-tests)
    uses: munich-quantum-toolkit/workflows/.github/workflows/reusable-python-linter.yml@v1.11

  code-ql:
    name: 📝 CodeQL
    needs: change-detection
    if: fromJSON(needs.change-detection.outputs.run-code-ql)
    uses: munich-quantum-toolkit/workflows/.github/workflows/reusable-code-ql.yml@v1.11

  cd:
    name: 🚀 CD
    needs: change-detection
    if: fromJSON(needs.change-detection.outputs.run-cd)
    uses: munich-quantum-toolkit/workflows/.github/workflows/reusable-python-packaging.yml@v1.11
    with:
      # Runs to enable
      enable-ubuntu2404: true
      enable-ubuntu2404-arm: true
      enable-macos13: true
      enable-macos14: true
      enable-windows2022: true
      enable-windows11-arm: true
      # Runs to disable
      enable-ubuntu2204: false
      enable-ubuntu2204-arm: false
      enable-macos15: false
      enable-windows2025: false

  required-checks-pass: # This job does nothing and is only used for branch protection
    name: 🚦 Check
    if: always()
    needs:
      - change-detection
      - rust-linter
      - python-linter
      - code-ql
      - cd
    runs-on: ubuntu-latest
    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@release/v1
        with:
          allowed-skips: >-
            ${{
              fromJSON(needs.change-detection.outputs.run-rust-linter)
              && '' || 'rust-linter,'
            }}
            ${{
              fromJSON(needs.change-detection.outputs.run-code-ql)
              && '' || 'code-ql,'
            }}
            ${{
              fromJSON(needs.change-detection.outputs.run-cd)
              && '' || 'cd,'
            }}
          jobs: ${{ toJSON(needs) }}
