name: 🐍 Lint

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  python-linter:
    name: 🐍 Lint
    uses: munich-quantum-toolkit/workflows/.github/workflows/reusable-python-linter.yml@v1.16
