# Copyright (c) 2023 - 2025 Chair for Design Automation, TUM
# Copyright (c) 2025 Munich Quantum Software Company GmbH
# All rights reserved.
#
# SPDX-License-Identifier: MIT
#
# Licensed under the MIT License

name: 🦀 • Tests • ubuntu
on:
  workflow_call:
    inputs:
      runs-on:
        description: >
          The ubuntu runner image to use. Defaults to 'ubuntu-latest'.
          This can be any valid ubuntu runner image, such as 'ubuntu-22.04', 'ubuntu-24.04', or their ARM variants 'ubuntu-22.04-arm', 'ubuntu-24.04-arm'.
        default: "ubuntu-latest"
        type: string
      config:
        description: >
          The build type to use. Defaults to 'Release'.
          This can be any valid CMake build type, such as 'Debug' or 'Release'.
        default: "Release"
        type: string

jobs:
  rust-tests-ubuntu:
    name: 🐧 ${{ inputs.runs-on }} ${{ inputs.config }}
    runs-on: ${{ inputs.runs-on }}
    env:
      CARGO_TERM_COLOR: always
    steps:
      # check out the repository (including submodules and all history)
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          submodules: recursive
          fetch-depth: 0
      # build the project in the specified mode with retries
      - name: Build
        run: cargo build --verbose --profile ${{ inputs.config }}
      # run the tests
      - name: Test
        run: cargo test --verbose --profile ${{ inputs.config }}
