name: 🦀 • Tests • windows
on:
  workflow_call:
    inputs:
      runs-on:
        description: >
          The Windows runner image to use. Defaults to 'windows-latest'.
          This can be any valid Windows runner image, such as 'windows-2022' or 'windows-2025'.
        default: "windows-latest"
        type: string
      config:
        description: >
          The build type to use. Defaults to 'Release'.
          This can be any valid CMake build type, such as 'Debug' or 'Release'.
        default: "Release"
        type: string

defaults:
  run:
    shell: bash

jobs:
  rust-tests-windows:
    name: 🏁 ${{ inputs.runs-on }} ${{ inputs.config }}
    runs-on: ${{ inputs.runs-on }}
    env:
      CARGO_TERM_COLOR: always
    steps:
      # check out the repository (including submodules and all history)
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          submodules: recursive
          fetch-depth: 0
      # build the project in the specified mode with retries
      - name: Build
        run: cargo build --verbose --profile ${{ inputs.config }}
      # run the tests
      - name: Test
        run: cargo test --verbose --profile ${{ inputs.config }}
